import type { FeuilletonConfig } from "@feuilleton/config";
import type { ArtifactRecord } from "@feuilleton/core";

export function buildAgentContext(config: FeuilletonConfig): string {
  const protocol =
    config.execution.mode === "inline"
      ? "To render terminal-native output, place a complete Bash script inside <ftn>...</ftn>. Do not call `ftn run` first: the script is executed automatically after your message completes."
      : 'To render terminal-native output, call `ftn run` with a Bash script on stdin, then copy the returned <ftn art="..."/> tag into your response.';
  const widgets = Object.entries(config.widgets)
    .map(
      ([name, widget]) =>
        `Widget ${name} (${widget.command}):\n${widget.description.trim()}`,
    )
    .join("\n\n");
  return [
    "Feuilleton display protocol:",
    protocol,
    "Use it for plots, trees, graphs, and other output that is clearer when generated by a terminal program.",
    "The script runs under Bash. Make it self-contained and syntactically valid because inline execution happens after the response and cannot be retried within that response.",
    "Do not include terminal dimensions in the script; the runtime provides them through environment variables.",
    widgets,
  ]
    .filter(Boolean)
    .join("\n\n");
}

export function buildArtifactContext(records: ArtifactRecord[]): string {
  if (!records.length) return "";
  return [
    "New Feuilleton artifacts are available. Read a file only if its output is needed:",
    ...records.map((r) => `- ${r.id}: ${r.stdoutPath}`),
  ].join("\n");
}
